### ISSUE TITLE
Can't find match Datasheet.

### ISSUE THREAD

**Issue by asergunov** [adafruit/Adafruit_GC9A01A#1]
There is comment in code referencing the datasheet:
```c++
uint8_t rtna =
        0x01; // Screen refresh rate control (datasheet 9.2.18, FRCTRL2)
```
But I can see only 7 chapters in manual. This one for example https://www.waveshare.com/w/upload/5/5e/GC9A01A.pdf

How can I find manual you are using?

**Comment by PaintYourDragon** [comment]
It’s possible that might have just been an accidental carry-over from another library such as ILI9341. Correct that this is not documented in the datasheet. It might have no effect. Will be looking into this and some other fixes as the library’s being transferred to Adafruit soon. Thanks for spotting this!
