### ISSUE TITLE
Missing numArgs byte in display initialization

### ISSUE THREAD

**Issue by Danjovic** [adafruit/Adafruit_GC9A01A#2]
Found some missing bytes in after the following commands in initcmd[] array that causes a different initialization bytes being sent to the display than what is intended.
```
static const uint8_t PROGMEM initcmd[] = {
...
  GC9A01A1_VREG1A, 0x13,
  GC9A01A1_VREG1B, 0x13,
  GC9A01A1_VREG2A, 0x22,
...
};
```
the three lines above should be  
``` 
  GC9A01A1_VREG1A, 1, 0x13,
  GC9A01A1_VREG1B, 1, 0x13,
  GC9A01A1_VREG2A, 1, 0x22,
```
  

So far the only effect of the different initialization I have noticed is a different default orientation and different collors on screen (for instance BLUE contents get painted in RED).
![image](https://user-images.githubusercontent.com/5844589/222917726-3935361d-2236-46e0-80e8-dd16d5360c34.png)

After I have included the missing bytes and recompiled the code I got the right colors but then running the Demo I got some "noise" lines on the image. I can see this same "noise" in the Waveshare example ~~, but haven't tracked its origin.~~ 

![image](https://user-images.githubusercontent.com/5844589/222918882-60e36abf-aea3-49dc-8272-0eecd36d6d50.png)

I have tracked this behavior to the command 0x70 which was also commented. Unfortunately the datasheet of the controller does not mention which is the purpose of such command.

```
static const uint8_t PROGMEM initcmd[] = {
...
  0xED, 2, 0x1B, 0x0B,
  0xAE, 1, 0x77,
  0xCD, 1, 0x63,
  // 0x70, 9, 0x07, 0x07, 0x04, 0x0E, 0x0F, 0x09, 0x07, 0x08, 0x03,
  ILI9341_FRAMERATE, 1, 0x34,
  0x62, 12, 0x18, 0x0D, 0x71, 0xED, 0x70, 0x70,
            0x18, 0x0F, 0x71, 0xEF, 0x70, 0x70,
...
};
```

**Comment by PaintYourDragon** [comment]
Thank you for spotting both of these! Will be fixed in the next commit shortly, and then I’ll be transferring the repo to Adafruit soon.
