### ISSUE TITLE
Variable redefined

### ISSUE THREAD

**Issue by TimTalma** [adafruit/Adafruit_GC9A01A#3]
In Adafruit_GC9A01A.cpp Line 47 and 48 are:
#define GC9A01A 0x04   ///< Read display identification information
#define GC9A01A 0x09   ///< Read Display Status

This gives a compile warning and is probably not the intended action

**Comment by PaintYourDragon** [comment]
Thanks for spotting this! Kinda amazing it even compiled.

This will be fixed in the next commit shortly, and then I’ll be transferring the repo to Adafruit soon.
